In [1]:
import os,sys,re,IPython,string
import numpy as np
import random
import matplotlib.pyplot as plt

# Basic numpy

In [ ]:
#4.1/A multidiensional array object
#-------------------------------------------------------------------
#Take information about array and Create table
data=np.random.randn(2,2,2,3)
data.shape# take the shape of matrix
data.size# total the number of element in martrix
data.ndim# the number of dimension of matrix(equal the n dimension of shape)
data.dtype# show the dtype of homgenenous data ( can connect to other system)
data_zero=np.zeros((10),dtype=int)# create the matrix(1,2) take every element is 0
data_one=np.ones((2,1))# corresponding the zeros matrix with 1
data_empty=np.empty((2,3))
######CAREFUL because it'l sometime not return every Os element
data_full=np.full(shape=(2,3),dtype=np.float32,fill_value=23)# Create a matrix with full element is (fill_value)
data_full_like=np.full_like(a=data_full,fill_value=100)# Like the another array by the shape and dtype(can change)
data_itendity=np.identity(n=4,dtype=np.float64)# create a identity array with 1s in diagonal and 0s in elsewhere (=np.eye(n=4)
#----------------------------------------------------------------
#dtype is important to consider what the kind of data that we need to use 
lst=[True,False,True,True]
data_lst_bool=np.array(lst,dtype=np.bool)# create array with true False value( can use more type is unicode,string,float32,float64)
data_lst_string=data_lst_bool.astype(dtype=np.string_)# Np.ASTYPE to convert from one type to another type
#convert from a array with dtype=float to dtype=int
array_float=np.random.randn(10)
array_int=array_float.astype(int)# always create a new array though 2 have the same dtype
array_float.astype(data_lst_string.dtype)# convert dtype of (a1)= dtype of (a2)
######CAREFUL when (np.string_) can truncate the float if have enough the byte
#---------------------------------------------------------------------
#Arithmetic with np.array
#Compute with scalar vector
array_23=np.array([[1.1,2.9,4.3],[4.5,2.3,1.2]],dtype=np.int16)
array_23**2# compute with dtype=int16 not by the original value
array_23>(array_23**0.5)# dtype=bool; create array with value True,False for each comparison value.(False we'll know this value<=1 and reverse)
#Basic Indexing and slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])# shape(3,3)
arr2d[0,1]# = array[0][1] just like to access nested list with pattern [row,column]
arr2d[2]=12# like [7,8,9]=[12,12,12] and when we slicing the matrix and change it the original'll be changed 
copy_subarr2d=arr2d[1].copy()# create array copy, when we changed this,original array'll not change
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])# shape(2,2,3)
arr3d[0].shape# shape(2,3)
arr2d[1:3,1:3]=arr2d[:2,1:3]# shape(2,2) with [array(row),array(column)]
#-----------------------------------------------------------------------
#Boolean Indexing
names=np.array(['ngoc','thach','ngoc','son','the'])#shape(5,)
data=np.random.randn(5,4)
#Boolean of True,False( create a copy)
data[names=='ngoc']#shape(2,2), take row=position of True (row 1,3)
data[names!='ngoc']#shape(1,2)( row 2,4,5)
data[(names=='ngoc')|(names=='thach')]# take row= 'ngoc' or 'thach' (row 1,2,3)
#Boolean of comparison
data[data<1]# shape (15,)
data[data<1]=10# set the value of array with the condition is (data<1)
data[[-5,-1,2]]=[[12],[11],[15]]#Pickking a submatrix with the list of positional row
data=np.arange(20).reshape(4,5)# combinate create a list of range(20) with reshape matrix(4,5)
data[[0,1,2,3],[0,1,2,3]]=[1,1,1,1]# Picking 1-darray value by each pair(row1,column1) and then assign this value to 1-darray [1,1,1,1]
print(data)
data[[1,2,3]][:,[1,2,3,4]] #first,take the submatrix with row=[[1,2,3]](no column), then from this submatrix we choose column=[:,[1,2,3,4]]
#---------------------------------------------------------------
###################Transposing and swap axes
data.T# transposing array by shape(a,b)=reshape(b,a)
data1=np.array([[1,1],[2,2]])
np.dot(data1.T,data1)# with a,b is 2-D array this formula (np.dot)'ll become mutiple 2 matrix
#transpose is permute the position with the corresponding axes
#With 2-d array:
arr2d=np.arange(6).reshape((2,3))# shape (2,3)
arr2d.transpose(1,0)#That means every coordinate of element'l be permuted: (0,0)->(0,0); (0,1)->(1,0);...;(1,2)->(2,1)
#with 3-d array:
arr3d=np.arange(24).reshape(2,3,4)
arr3d.transpose(1,2,0)# that means:(0,1,2)->(1,2,0)=6;(1,2,3)->(2,3,1)=22
arr3d.swapaxes(1,2)#means that swap position of pair(1,2) and (0) not change: (0,1,2)->(0,2,1)
#-------------------------------------------------------------------
#Universal Function(ufunc) is the function with element-wise array
arr2d=np.arange(16).reshape(4,4)
arr2d.astype(dtype=np.int16)
exp_arr2d=np.exp(arr2d)# e^i with i is element-wise array
# ufunc can return a multiple result 
fractional,integral=np.modf(exp_arr2d)#return 2 array with [fractional],[integral] element-wise of x
# unary ufunc from binary ufuncs with (maximum,minimum)
np.maximum(arr2d,integral,fractional)# return a unary ufuncs that have the maximum of element-wise from array combination
#Some unary ufuncs:( abs,fabs),(sqrt,square),(log,log10,log2),(ceil,floor),(isnan,isfinite,isinf),(cos,arccos,)
#Some binary ufuncs:(add,subtract,multiply,divide,floor_divide(truncating the remainder),power),(maximum,fmax(with non-NaN)),(greate_equal,greater,not_equal),(logical_and,or,xor(&,|,^))


# 4.3Array-Oriented Programming with Arrays

#### EXPRESSING CONDITIONAL LOGIC AS ARRAY OPERATIONS
Meshgrid()

np.where(condition,x,y)

In [ ]:
# np.meshgrid is take 2D from 1D that is a point
point=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(point,point)
z=np.sqrt(xs**2+ys**2)
# Np.where with conditional list
xarr=np.arange(0,10,2).reshape(1,5)
yarr=np.arange(1,11,2).reshape(1,5)
condi=np.array([True,False,False,True,False])#shape(1,5)
arr=np.where(condi,xarr,yarr)#consider element in condi.Element of (xarr,yarr)=Element of (True,False)
arr=np.where(condi.reshape(5,1),xarr,yarr)# (xarr,yarr)=element of [[True],[False]]
# np.where with condition array 
arr=np.random.randn(4,4)
arr=np.where(arr>0,arr,'negative')# retain arr[element] when element of arr>0, and 'negative' when element of arr<0


### Mathematical and Statistical Methods
Reduction with aggregation

Sum,Mean,Std,Cumsum,cumprod,max,min

In [ ]:
#Reduction dimension by use aggregations like SUM,Mean,Standard Deviation
arr=np.arange(20).reshape(4,5)
arr
arr.sum(axis=1)# sum of 5 element in axis=1(=5).That reduce to shape(4,1),ndim=1
arr.mean(axis=0)# mean of 4 element in axis=0(=4).That reduce to shape(5,1),ndim=1
arr1=np.arange(24).reshape(2,3,4)
arr1
arr1.sum(axis=2)# reduce to (2,3,1) ,for short to reduce to (2,3).That means we reduce from n.dim=3 to n.dim=2
#The aggregation don't reduce the dimension like CUMSUM,CUMPROD( cummulative sum)
arr.cumsum(axis=1)# cummulative sum of 5 element from the first element of each row
arr.cumprod(axis=0)# cumulative product of 4 element in each column
arr1.cumsum(axis=0)# cumsum of element-wise of first.shape(3,4) with second.shape(3,4),respectively
arr1.max(axis=2).cumsum(axis=0)# combination max and cumsum.( sequence is do cumsum(axis=0) first then from this do max(axis=2))

### Methods for Boolean Arrays
Sum of True

Any(),ALL()

In [46]:
#Because (True=1, False=0), thus when we use sum() we default sum of True=1
arr=np.random.randn(10)
(arr>0).sum()# sum of True= count of True because True=1
#Checks some value is true or false with(ANY,ALL)
(arr>0).any()#return True if have at least True in this array
arr1=np.array([True,True,True,True]).reshape(2,2)
arr.all()# return True is all of true in this array

True

### Sorting

In [ ]:
arr=np.random.randn(2,3,4)
sort_arr=np.sort(a=arr,axis=2).copy()#make a copy of array with sorted
arr.sort(axis=2)# change the original of arr with sort(combination of axis=2)

### Unique and Other set logic
np.unique(ar1,ar2)

In [ ]:
arr=np.array(['ngoc','ngoc','son','the','ngoc','thach']).reshape(2,3)
np.sort(a=np.unique(ar=arr))# Sort by the unique string in array
#Use unique on the 2-d array with the same type of loop value
arr1=np.array([[1,2,1],[2,3,2],[3,4,3]]).reshape(3,3)
np.unique(ar=arr1,axis=1)# return the shape(3,2) that removed the value that occured 2 times
#Use unique to check value if that in the unique list
np.in1d(ar1=arr,ar2=['ngoc','thach'])# ar1 is refered array. ar2 contains element need to check

### File Input and Output with Arrays
Save and Load file .npy/.npz

In [ ]:
#Save one array in a file (.npy) with np.save
arr=np.arange(24).reshape(2,3,4)
file_save=np.save(file='file_save',arr=arr)
f_load=np.load(file='file_save.npy')
f_load
#Save multiple array in a file (.npz) with np.savez
arr1=np.arange(36).reshape(6,6)
np.savez(file='file_save1',arr=arr,arr1=arr1)
file_load1=np.load(file='file_save1.npz')
file_load1['arr']# call the variable that contains that arr

## 4.5 Linear Algebra

In [21]:
#Muptiply 2 matrix
arr=np.array([1,2,3,7,9,10]).reshape(2,3)
arr1=np.array([2,3,4,1,5,2]).reshape(3,2)
arr.dot(arr1)# return the array(3,3) that is muptiply by 2 matrix
arr@ arr1 # like arr.dot(arr1) when both is 2-d array
arr*arr1.T# muptiply by element-wise between 2 matrix
arr.dot(3)# mupltiply array with scalar array as array*n
arr1=np.arange(24).reshape(2,3,4)
# np.linalg (numpy.linear algebra)with inv,
arr=np.arange(6).reshape(2,3)
mat=arr.T.dot(arr)# return a symmetric matrix 
try:
    mat.dot(np.linalg.inv(mat))
except:
    pass #return a singular matrix because row2=row1*n, row3=row2*m,...
a,b=qr(mat) #q is orthorgonal matrix and r is upper matrix

[[ 9 12 15]
 [12 17 22]
 [15 22 29]]


array([[-0.42426407,  0.80829038,  0.40824829],
       [-0.56568542,  0.11547005, -0.81649658],
       [-0.70710678, -0.57735027,  0.40824829]])

## 4.6 Pseudorandom Number Generation
#### Normal distribution by np.normal()

In [12]:
#Normal distribution
sample=np.random.normal(size=(3,2))# create a random normal distribution 
sample1=np.random.standard_normal(size=(4,4))# create a standard normal distribution
# The random number of this distributioin is generated by an algorithm.
# we can change the seed of an algorithm
np.random.seed(seed=100) # seed is used for global seed
np.random.RandomState(seed=1000) # use for creating a random number that is isolated from others

## 4.7 Example: Random Walks

In [60]:
#Random walk starting from 0 with steps of 1 and -1 
nsteps=1000
nwalks=5000
sample=np.random.randint(0,2,size=(nwalks,nsteps))# set up the array(5k,1k) with only value 0,1
sample=np.where(sample>0,1,-1)# set 1 if sample >0, set -1 else
walks=sample.cumsum(axis=1)
print(walks)
walks.min()
np.abs(walks)>=10# set TrueFalse array with |walks|>=10
abs30=(np.abs(walks)>=30).any(axis=1)# return True=1, False=0 array if abs(walks)>=30
print(abs30)
abs30.sum()#count of True as count of abs(walks)>=30


[[ -1   0  -1 ... -10 -11 -12]
 [  1   2   3 ... -22 -21 -20]
 [  1   2   1 ... -68 -67 -68]
 ...
 [  1   2   3 ... -38 -37 -36]
 [  1   2   3 ... -28 -29 -28]
 [  1   0  -1 ...  44  43  42]]
[False False  True ...  True  True  True]


3425